import type { Course, LearningPath, AssessmentQuestion, Project, UserProgress, Analytics } from "@shared/schema";

export const mockCourses: Course[] = [
  {
    id: "1",
    title: "Complete Web Development Bootcamp",
    description: "Learn HTML, CSS, JavaScript, React, Node.js, and more. Build real-world projects and become a full-stack developer.",
    provider: "udemy",
    category: "development",
    difficulty: "beginner",
    duration: "63 hours",
    rating: 4.7,
    reviewCount: 245000,
    instructor: "Dr. Angela Yu",
    thumbnailUrl: "https://images.unsplash.com/photo-1461749280684-dccba630e2f6?w=400&h=225&fit=crop",
    syllabus: [
      { week: 1, title: "HTML Fundamentals", topics: ["HTML basics", "Semantic HTML", "Forms"], duration: "8 hours" },
      { week: 2, title: "CSS Mastery", topics: ["CSS selectors", "Flexbox", "Grid", "Animations"], duration: "10 hours" },
      { week: 3, title: "JavaScript Essentials", topics: ["Variables", "Functions", "DOM manipulation"], duration: "12 hours" },
      { week: 4, title: "React Development", topics: ["Components", "State", "Hooks", "Context"], duration: "15 hours" },
      { week: 5, title: "Backend with Node.js", topics: ["Express", "REST APIs", "MongoDB"], duration: "18 hours" },
    ],
    skills: ["HTML", "CSS", "JavaScript", "React", "Node.js", "MongoDB"],
    price: 89.99,
  },
  {
    id: "2",
    title: "Machine Learning Specialization",
    description: "Master machine learning with Python. Learn supervised learning, neural networks, and deep learning from Stanford professors.",
    provider: "coursera",
    category: "data-science",
    difficulty: "intermediate",
    duration: "3 months",
    rating: 4.9,
    reviewCount: 180000,
    instructor: "Andrew Ng",
    thumbnailUrl: "https://images.unsplash.com/photo-1555949963-aa79dcee981c?w=400&h=225&fit=crop",
    syllabus: [
      { week: 1, title: "Supervised Learning", topics: ["Linear regression", "Logistic regression", "Gradient descent"], duration: "20 hours" },
      { week: 2, title: "Advanced Algorithms", topics: ["Neural networks", "Decision trees", "Ensemble methods"], duration: "25 hours" },
      { week: 3, title: "Unsupervised Learning", topics: ["Clustering", "Dimensionality reduction", "Anomaly detection"], duration: "20 hours" },
      { week: 4, title: "Deep Learning", topics: ["CNNs", "RNNs", "Transformers"], duration: "30 hours" },
    ],
    skills: ["Python", "TensorFlow", "Machine Learning", "Neural Networks", "Data Analysis"],
    price: 49,
  },
  {
    id: "3",
    title: "UI/UX Design Masterclass",
    description: "Learn user interface and user experience design from scratch. Create stunning designs with Figma and build your portfolio.",
    provider: "udemy",
    category: "design",
    difficulty: "beginner",
    duration: "28 hours",
    rating: 4.6,
    reviewCount: 95000,
    instructor: "Daniel Walter Scott",
    thumbnailUrl: "https://images.unsplash.com/photo-1561070791-2526d30994b5?w=400&h=225&fit=crop",
    syllabus: [
      { week: 1, title: "Design Fundamentals", topics: ["Color theory", "Typography", "Layout principles"], duration: "6 hours" },
      { week: 2, title: "Figma Mastery", topics: ["Interface overview", "Components", "Auto-layout"], duration: "8 hours" },
      { week: 3, title: "UX Research", topics: ["User personas", "Journey mapping", "Usability testing"], duration: "7 hours" },
      { week: 4, title: "Portfolio Projects", topics: ["Mobile app design", "Web design", "Case studies"], duration: "7 hours" },
    ],
    skills: ["Figma", "UI Design", "UX Research", "Prototyping", "Design Systems"],
    price: 79.99,
  },
  {
    id: "4",
    title: "Digital Marketing Specialization",
    description: "Master digital marketing strategies including SEO, social media, content marketing, and analytics.",
    provider: "coursera",
    category: "marketing",
    difficulty: "beginner",
    duration: "6 months",
    rating: 4.5,
    reviewCount: 120000,
    instructor: "University of Illinois",
    thumbnailUrl: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=400&h=225&fit=crop",
    syllabus: [
      { week: 1, title: "Marketing Fundamentals", topics: ["Brand strategy", "Consumer behavior", "Market research"], duration: "15 hours" },
      { week: 2, title: "SEO & SEM", topics: ["Keyword research", "On-page SEO", "Google Ads"], duration: "20 hours" },
      { week: 3, title: "Social Media Marketing", topics: ["Platform strategies", "Content creation", "Influencer marketing"], duration: "18 hours" },
      { week: 4, title: "Analytics & Optimization", topics: ["Google Analytics", "A/B testing", "ROI measurement"], duration: "15 hours" },
    ],
    skills: ["SEO", "Google Ads", "Social Media", "Content Marketing", "Analytics"],
    price: 39,
  },
  {
    id: "5",
    title: "Data Science Professional Certificate",
    description: "Become a data scientist with hands-on experience in Python, SQL, data visualization, and machine learning.",
    provider: "coursera",
    category: "data-science",
    difficulty: "intermediate",
    duration: "10 months",
    rating: 4.6,
    reviewCount: 85000,
    instructor: "IBM",
    thumbnailUrl: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=400&h=225&fit=crop",
    syllabus: [
      { week: 1, title: "Python for Data Science", topics: ["Python basics", "Pandas", "NumPy"], duration: "25 hours" },
      { week: 2, title: "SQL & Databases", topics: ["SQL queries", "Database design", "Data modeling"], duration: "20 hours" },
      { week: 3, title: "Data Visualization", topics: ["Matplotlib", "Seaborn", "Plotly"], duration: "18 hours" },
      { week: 4, title: "Machine Learning Projects", topics: ["Classification", "Regression", "Model deployment"], duration: "30 hours" },
    ],
    skills: ["Python", "SQL", "Data Visualization", "Machine Learning", "Statistics"],
    price: 39,
  },
  {
    id: "6",
    title: "Business Strategy Specialization",
    description: "Develop strategic thinking skills and learn to create sustainable competitive advantages for businesses.",
    provider: "coursera",
    category: "business",
    difficulty: "advanced",
    duration: "4 months",
    rating: 4.7,
    reviewCount: 65000,
    instructor: "University of Virginia",
    thumbnailUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=225&fit=crop",
    syllabus: [
      { week: 1, title: "Strategic Analysis", topics: ["Industry analysis", "Competitive forces", "Value chain"], duration: "20 hours" },
      { week: 2, title: "Growth Strategies", topics: ["Market expansion", "Diversification", "M&A"], duration: "18 hours" },
      { week: 3, title: "Innovation Management", topics: ["Disruptive innovation", "Business model innovation", "Digital transformation"], duration: "20 hours" },
      { week: 4, title: "Strategy Execution", topics: ["KPIs", "Balanced scorecard", "Change management"], duration: "15 hours" },
    ],
    skills: ["Strategic Planning", "Business Analysis", "Leadership", "Decision Making", "Innovation"],
    price: 49,
  },
  {
    id: "7",
    title: "React Native - Mobile App Development",
    description: "Build cross-platform mobile apps for iOS and Android using React Native and JavaScript.",
    provider: "udemy",
    category: "development",
    difficulty: "intermediate",
    duration: "35 hours",
    rating: 4.8,
    reviewCount: 72000,
    instructor: "Maximilian Schwarzmüller",
    thumbnailUrl: "https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=400&h=225&fit=crop",
    syllabus: [
      { week: 1, title: "React Native Basics", topics: ["Setup", "Components", "Styling"], duration: "8 hours" },
      { week: 2, title: "Navigation & State", topics: ["React Navigation", "Redux", "Context API"], duration: "10 hours" },
      { week: 3, title: "Native Features", topics: ["Camera", "Location", "Push notifications"], duration: "10 hours" },
      { week: 4, title: "Publishing Apps", topics: ["App Store", "Google Play", "CI/CD"], duration: "7 hours" },
    ],
    skills: ["React Native", "JavaScript", "iOS", "Android", "Mobile Development"],
    price: 94.99,
  },
  {
    id: "8",
    title: "Personal Productivity Masterclass",
    description: "Master time management, goal setting, and productivity techniques to achieve more in less time.",
    provider: "udemy",
    category: "personal-development",
    difficulty: "beginner",
    duration: "12 hours",
    rating: 4.5,
    reviewCount: 150000,
    instructor: "Thomas Frank",
    thumbnailUrl: "https://images.unsplash.com/photo-1484480974693-6ca0a78fb36b?w=400&h=225&fit=crop",
    syllabus: [
      { week: 1, title: "Goal Setting", topics: ["SMART goals", "Vision boards", "Priority matrix"], duration: "3 hours" },
      { week: 2, title: "Time Management", topics: ["Pomodoro technique", "Time blocking", "Energy management"], duration: "4 hours" },
      { week: 3, title: "Focus & Deep Work", topics: ["Eliminating distractions", "Flow state", "Mindfulness"], duration: "3 hours" },
      { week: 4, title: "Habit Building", topics: ["Habit stacking", "Tracking progress", "Accountability"], duration: "2 hours" },
    ],
    skills: ["Time Management", "Goal Setting", "Focus", "Habit Building", "Productivity"],
    price: 49.99,
  },
  {
    id: "9",
    title: "Advanced Python Programming",
    description: "Take your Python skills to the next level with advanced concepts, design patterns, and real-world applications.",
    provider: "udemy",
    category: "development",
    difficulty: "advanced",
    duration: "45 hours",
    rating: 4.7,
    reviewCount: 58000,
    instructor: "Fred Baptiste",
    thumbnailUrl: "https://images.unsplash.com/photo-1526379095098-d400fd0bf935?w=400&h=225&fit=crop",
    syllabus: [
      { week: 1, title: "Advanced OOP", topics: ["Metaclasses", "Descriptors", "Abstract classes"], duration: "12 hours" },
      { week: 2, title: "Functional Programming", topics: ["Decorators", "Generators", "Coroutines"], duration: "10 hours" },
      { week: 3, title: "Concurrency", topics: ["Threading", "Multiprocessing", "Async/await"], duration: "13 hours" },
      { week: 4, title: "Design Patterns", topics: ["Creational", "Structural", "Behavioral patterns"], duration: "10 hours" },
    ],
    skills: ["Python", "OOP", "Design Patterns", "Concurrency", "Software Architecture"],
    price: 99.99,
  },
];

export const mockLearningPaths: LearningPath[] = [
  {
    id: "lp1",
    title: "Full-Stack Web Developer",
    description: "Become a complete web developer with frontend and backend skills. Build modern web applications from scratch.",
    category: "development",
    difficulty: "beginner",
    estimatedDuration: "6 months",
    courses: ["1", "7"],
    skills: ["HTML", "CSS", "JavaScript", "React", "Node.js", "MongoDB"],
  },
  {
    id: "lp2",
    title: "Data Science & Machine Learning",
    description: "Master data science and machine learning from fundamentals to advanced concepts. Work with real datasets and build ML models.",
    category: "data-science",
    difficulty: "intermediate",
    estimatedDuration: "8 months",
    courses: ["2", "5"],
    skills: ["Python", "Machine Learning", "Data Analysis", "TensorFlow", "Statistics"],
  },
  {
    id: "lp3",
    title: "Digital Marketing Professional",
    description: "Develop comprehensive digital marketing skills from SEO to social media. Create and execute marketing campaigns.",
    category: "marketing",
    difficulty: "beginner",
    estimatedDuration: "4 months",
    courses: ["4"],
    skills: ["SEO", "Social Media", "Content Marketing", "Analytics", "Google Ads"],
  },
  {
    id: "lp4",
    title: "Product Design Expert",
    description: "Learn UI/UX design principles and tools. Create beautiful, user-centered designs for digital products.",
    category: "design",
    difficulty: "beginner",
    estimatedDuration: "3 months",
    courses: ["3"],
    skills: ["Figma", "UI Design", "UX Research", "Prototyping", "Design Systems"],
  },
];

export const mockAssessmentQuestions: AssessmentQuestion[] = [
  {
    id: "q1",
    question: "What does HTML stand for?",
    options: ["Hyper Text Markup Language", "High Tech Modern Language", "Home Tool Markup Language", "Hyperlinks and Text Markup Language"],
    correctAnswer: 0,
    category: "development",
    difficulty: "beginner",
  },
  {
    id: "q2",
    question: "Which programming language is primarily used for data science?",
    options: ["Java", "Python", "C++", "Ruby"],
    correctAnswer: 1,
    category: "data-science",
    difficulty: "beginner",
  },
  {
    id: "q3",
    question: "What is the primary purpose of SEO?",
    options: ["Social media management", "Email marketing", "Search engine visibility", "Paid advertising"],
    correctAnswer: 2,
    category: "marketing",
    difficulty: "beginner",
  },
  {
    id: "q4",
    question: "What is the difference between UI and UX design?",
    options: [
      "UI focuses on visuals, UX on user experience",
      "They are the same thing",
      "UI is for mobile, UX for web",
      "UX is coding, UI is design"
    ],
    correctAnswer: 0,
    category: "design",
    difficulty: "beginner",
  },
  {
    id: "q5",
    question: "What is React primarily used for?",
    options: ["Database management", "Building user interfaces", "Server configuration", "Machine learning"],
    correctAnswer: 1,
    category: "development",
    difficulty: "intermediate",
  },
  {
    id: "q6",
    question: "Which algorithm is commonly used for classification problems?",
    options: ["Linear Regression", "K-means Clustering", "Random Forest", "PCA"],
    correctAnswer: 2,
    category: "data-science",
    difficulty: "intermediate",
  },
  {
    id: "q7",
    question: "What is A/B testing in marketing?",
    options: [
      "Testing between agencies A and B",
      "Comparing two versions to see which performs better",
      "Testing in two different countries",
      "Automated testing of ads"
    ],
    correctAnswer: 1,
    category: "marketing",
    difficulty: "intermediate",
  },
  {
    id: "q8",
    question: "What is a design system?",
    options: [
      "A computer operating system for designers",
      "A collection of reusable components and guidelines",
      "A type of software",
      "A design school curriculum"
    ],
    correctAnswer: 1,
    category: "design",
    difficulty: "intermediate",
  },
  {
    id: "q9",
    question: "Which principle is NOT part of SOLID in software design?",
    options: ["Single Responsibility", "Open/Closed", "Linked Dependency", "Dependency Inversion"],
    correctAnswer: 2,
    category: "development",
    difficulty: "advanced",
  },
  {
    id: "q10",
    question: "What is the primary goal of strategic planning in business?",
    options: [
      "Day-to-day operations",
      "Long-term direction and resource allocation",
      "Employee scheduling",
      "Product packaging"
    ],
    correctAnswer: 1,
    category: "business",
    difficulty: "intermediate",
  },
];

export const mockProjects: Project[] = [
  {
    id: "p1",
    title: "Personal Portfolio Website",
    description: "Build a responsive portfolio website showcasing your projects and skills using HTML, CSS, and JavaScript.",
    difficulty: "beginner",
    estimatedTime: "15 hours",
    skills: ["HTML", "CSS", "JavaScript", "Responsive Design"],
    requirements: [
      "Home page with introduction",
      "Projects gallery with filtering",
      "Contact form with validation",
      "Mobile-responsive design"
    ],
    learningOutcomes: [
      "Master HTML5 semantic elements",
      "Create responsive layouts with CSS Grid and Flexbox",
      "Implement JavaScript form validation",
      "Deploy a website to production"
    ],
    courseId: "1",
  },
  {
    id: "p2",
    title: "E-commerce Product Recommendation System",
    description: "Build a machine learning model that recommends products based on user behavior and purchase history.",
    difficulty: "advanced",
    estimatedTime: "40 hours",
    skills: ["Python", "Machine Learning", "Collaborative Filtering", "Data Analysis"],
    requirements: [
      "Data preprocessing pipeline",
      "Collaborative filtering algorithm",
      "Model evaluation metrics",
      "API endpoint for predictions"
    ],
    learningOutcomes: [
      "Implement recommendation algorithms",
      "Handle sparse matrices efficiently",
      "Evaluate model performance",
      "Deploy ML models as APIs"
    ],
    courseId: "2",
  },
  {
    id: "p3",
    title: "Mobile App UI Redesign",
    description: "Redesign an existing mobile app to improve user experience and visual appeal using Figma.",
    difficulty: "intermediate",
    estimatedTime: "20 hours",
    skills: ["Figma", "UI Design", "UX Research", "Prototyping"],
    requirements: [
      "User research and persona creation",
      "Wireframes for key screens",
      "High-fidelity mockups",
      "Interactive prototype"
    ],
    learningOutcomes: [
      "Conduct effective user research",
      "Create user-centered designs",
      "Build interactive prototypes",
      "Present design decisions"
    ],
    courseId: "3",
  },
  {
    id: "p4",
    title: "Social Media Marketing Campaign",
    description: "Plan and execute a complete social media marketing campaign for a small business.",
    difficulty: "intermediate",
    estimatedTime: "25 hours",
    skills: ["Social Media", "Content Marketing", "Analytics", "Campaign Strategy"],
    requirements: [
      "Target audience analysis",
      "Content calendar for 1 month",
      "Campaign performance tracking",
      "ROI report and recommendations"
    ],
    learningOutcomes: [
      "Develop audience personas",
      "Create engaging content strategies",
      "Measure campaign effectiveness",
      "Optimize based on data"
    ],
    courseId: "4",
  },
];

export const mockUserProgress: UserProgress[] = [
  {
    id: "up1",
    courseId: "1",
    completedModules: [1, 2],
    progressPercent: 40,
    startedAt: "2024-01-15T10:00:00Z",
    lastAccessedAt: "2024-01-28T14:30:00Z",
    timeSpentMinutes: 1260,
  },
  {
    id: "up2",
    courseId: "3",
    completedModules: [1],
    progressPercent: 25,
    startedAt: "2024-01-20T09:00:00Z",
    lastAccessedAt: "2024-01-27T16:45:00Z",
    timeSpentMinutes: 420,
  },
];

export const mockAnalytics: Analytics = {
  totalCoursesStarted: 4,
  totalCoursesCompleted: 1,
  totalTimeSpentMinutes: 2580,
  averageProgress: 45,
  skillsAcquired: ["HTML", "CSS", "JavaScript basics", "Design fundamentals"],
  weeklyActivity: [
    { day: "Mon", minutes: 120 },
    { day: "Tue", minutes: 90 },
    { day: "Wed", minutes: 150 },
    { day: "Thu", minutes: 60 },
    { day: "Fri", minutes: 180 },
    { day: "Sat", minutes: 240 },
    { day: "Sun", minutes: 45 },
  ],
  categoryDistribution: {
    development: 60,
    design: 25,
    "data-science": 10,
    business: 5,
  },
  streakDays: 12,
};
